# ── Single Secrets Manager secret for the entire Plutus project ───────────────

resource "random_password" "insights_bearer_token" {
  length  = 48
  special = false # URL-safe, no escaping headaches in headers
}

resource "aws_secretsmanager_secret" "plutus" {
  name        = "plutus/secrets"
  description = "All secrets for the Plutus project (API keys, bearer tokens)"

  tags = { Project = "Plutus" }
}

resource "aws_secretsmanager_secret_version" "plutus" {
  secret_id = aws_secretsmanager_secret.plutus.id

  secret_string = jsonencode({
    # ── Bearer token for the insights Lambda Function URL ──────────────────
    # Used by the Flutter app in the Authorization: Bearer <token> header.
    # Auto-generated by Terraform — do not edit manually.
    INSIGHTS_BEARER_TOKEN = random_password.insights_bearer_token.result

    # ── Google OAuth ───────────────────────────────────────────────────────
    # Paste your new rotated values here after running terraform apply.
    GOOGLE_CLIENT_SECRET         = "REPLACE_WITH_ROTATED_VALUE"
    GOOGLE_DESKTOP_CLIENT_SECRET = "REPLACE_WITH_ROTATED_VALUE"

    # ── External API keys ──────────────────────────────────────────────────
    EXCHANGE_RATE_API_KEY = "REPLACE_WITH_ROTATED_VALUE"
    COINGECKO_API_KEY     = "REPLACE_WITH_ROTATED_VALUE"
    ALPHA_VANTAGE_API_KEY = "REPLACE_WITH_ROTATED_VALUE"

    # ── AWS credentials (for Flutter app S3/Textract access) ──────────────
    # These are long-lived IAM keys embedded in the app — a known risk (FIND-002).
    # Paste your new rotated values here.
    PLUTUS_AWS_ACCESS_KEY_ID     = "REPLACE_WITH_ROTATED_VALUE"
    PLUTUS_AWS_SECRET_ACCESS_KEY = "REPLACE_WITH_ROTATED_VALUE"
  })

  # Prevent terraform apply from overwriting values you've manually updated
  # in the AWS Console (e.g. after rotating API keys).
  # To force a refresh, use: terraform taint aws_secretsmanager_secret_version.plutus
  lifecycle {
    ignore_changes = [secret_string]
  }
}

# ── IAM policy: allow insights Lambda to read this secret ─────────────────────

resource "aws_iam_role_policy" "ai_insights_secrets" {
  name = "plutus-ai-insights-secrets"
  role = aws_iam_role.ai_insights_role.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = ["secretsmanager:GetSecretValue"]
      Resource = aws_secretsmanager_secret.plutus.arn
    }]
  })
}
