import 'package:flutter/material.dart';
import '../../theme/app_spacing.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../models/investment_model.dart';
import '../services/interfaces/i_investment_service.dart';
import '../di/service_locator.dart';
import '../providers/auth_notifier.dart';
import '../widgets/glass_container.dart';
import '../widgets/glass_background.dart';
import '../widgets/add_investment_dialog.dart';
import '../l10n/app_localizations.dart';
import '../theme/app_colors.dart';

/// Full screen view of all investments
class InvestmentListScreen extends ConsumerStatefulWidget {
  const InvestmentListScreen({super.key});

  @override
  ConsumerState<InvestmentListScreen> createState() => _InvestmentListScreenState();
}

class _InvestmentListScreenState extends ConsumerState<InvestmentListScreen> {
  final IInvestmentService _service = sl<IInvestmentService>();
  List<InvestmentModel>? _investments;
  bool _isLoading = false;
  String? _error;

  @override
  void initState() {
    super.initState();
    // Set user ID in the investment service for database operations
    final authNotifier = ref.read(authNotifierProvider.notifier);
    if (authNotifier.currentUserId != null) {
      _service.setUserId(authNotifier.currentUserId!);
    }
    _loadData();
  }

  Future<void> _loadData() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      final investments = await _service.getInvestmentList(forceRefresh: true);
      if (mounted) {
        setState(() {
          _investments = investments;
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _error = e.toString();
          _isLoading = false;
        });
      }
    }
  }

  void _showAddDialog() {
    showDialog(
      context: context,
      builder: (context) => AddInvestmentDialog(
        onSave: (assetType, assetName, quantity, purchaseValue, currency, purchaseDate) async {
          try {
            // Show loading state
            setState(() {
              _isLoading = true;
              _error = null;
            });
            
            // Create investment model
            final investment = InvestmentModel(
              id: '', // Will be generated by backend
              assetType: assetType,
              assetName: assetName,
              quantity: quantity,
              purchaseValue: purchaseValue,
              currency: currency,
              purchaseDate: purchaseDate,
            );
            
            // Save to backend (this fetches price data)
            final service = sl<IInvestmentService>();
            final authNotifier = ref.read(authNotifierProvider.notifier);
            if (authNotifier.currentUserId != null) {
              service.setUserId(authNotifier.currentUserId!);
            }
            await service.saveInvestment(investment);
            
            if (context.mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text('$assetName added to your portfolio'),
                  backgroundColor: AppColors.success,
                ),
              );

              // Reload data to show the new investment with price
              await _loadData();
            }
          } catch (e) {
            if (context.mounted) {
              setState(() {
                _isLoading = false;
              });
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: const Text("Couldn't add investment. Please try again."),
                  backgroundColor: AppColors.error,
                ),
              );
            }
          }
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final localizations = AppLocalizations.of(context);
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      backgroundColor: Colors.transparent,
      body: GlassBackground(
        child: SafeArea(
          child: Column(
            children: [
              // App bar
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Row(
                  children: [
                    IconButton(
                      icon: const Icon(Icons.arrow_back),
                      onPressed: () => context.pop(),
                      color: isDark ? AppColors.textOnDark : AppColors.textOnLight,
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Text(
                      localizations.investments,
                      style: Theme.of(context).textTheme.headlineMedium?.copyWith(
                            fontWeight: FontWeight.bold,
                            color: isDark ? AppColors.textOnDark : AppColors.textOnLight,
                          ),
                    ),
                  ],
                ),
              ),
              
              // Content
              Expanded(
                child: DefaultTabController(
                  length: 2,
                  child: Column(
                    children: [
                      TabBar(
                        labelColor: isDark ? AppColors.textOnDark : AppColors.textOnLight,
                        tabs: [
                          Tab(text: localizations.investmentTabActive),
                          Tab(text: localizations.investmentTabClosed),
                        ],
                      ),
                      Expanded(
                        child: TabBarView(
                          children: [
                            _buildContent(localizations, isDark, closed: false),
                            _buildContent(localizations, isDark, closed: true),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAddDialog,
        backgroundColor: AppColors.primaryDark,
        child: const Icon(Icons.add, color: Colors.white),
      ),
    );
  }

  Widget _buildContent(AppLocalizations localizations, bool isDark, {required bool closed}) {
    if (_isLoading) {
      return const Center(
        child: CircularProgressIndicator(color: AppColors.primary),
      );
    }

    if (_error != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.error_outline, size: 64, color: AppColors.error),
            const SizedBox(height: AppSpacing.lg),
            Text(
              localizations.errorLoadingData,
              style: const TextStyle(color: AppColors.error, fontSize: 18),
            ),
            const SizedBox(height: AppSpacing.sm),
            Text(
              _error!,
              style: TextStyle(color: AppColors.error.withValues(alpha: 0.7)),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            ElevatedButton(
              onPressed: _loadData,
              child: Text(localizations.retry),
            ),
          ],
        ),
      );
    }

    final all = _investments ?? const <InvestmentModel>[];
    final filtered = all.where((i) => i.isClosed == closed).toList();

    if (filtered.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(
              Icons.account_balance_wallet_outlined,
              size: 64,
              color: isDark ? AppColors.textOnDarkTertiary : AppColors.textOnLightTertiary,
            ),
            const SizedBox(height: AppSpacing.lg),
            Text(
              closed ? localizations.investmentNoClosed : localizations.noInvestmentsYet,
              style: TextStyle(
                fontSize: 18,
                color: isDark ? AppColors.textOnDarkSecondary : AppColors.textOnLightSecondary,
              ),
            ),
          ],
        ),
      );
    }

    return RefreshIndicator(
      onRefresh: _loadData,
      child: ListView.builder(
        padding: const EdgeInsets.all(16),
        itemCount: filtered.length,
        itemBuilder: (context, index) {
          return _buildInvestmentCard(filtered[index], isDark);
        },
      ),
    );
  }

  Widget _buildInvestmentCard(InvestmentModel investment, bool isDark) {
    final color = investment.isPositiveReturn()
        ? (isDark ? AppColors.accent : AppColors.primaryDark)
        : AppColors.error;

    return GlassContainer(
      borderRadius: 12,
      opacity: isDark ? 0.3 : 0.1,
      margin: const EdgeInsets.only(bottom: 12),
      child: ListTile(
        contentPadding: const EdgeInsets.all(16),
        title: Text(
          investment.assetName,
          style: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.bold,
            color: isDark ? AppColors.textOnDark : AppColors.textOnLight,
          ),
        ),
        subtitle: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: AppSpacing.xs),
            Text(
              '${investment.assetType.name.toUpperCase()} • ${investment.quantity} units',
              style: TextStyle(
                fontSize: 12,
                color: isDark ? AppColors.textOnDarkSecondary : AppColors.textOnLightSecondary,
              ),
            ),
            const SizedBox(height: AppSpacing.sm),
            Row(
              children: [
                Text(
                  '${investment.getCurrencySymbol()}${investment.getCurrentValue().toStringAsFixed(2)}',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.w600,
                    color: isDark ? AppColors.textOnDark : AppColors.textOnLight,
                  ),
                ),
                const SizedBox(width: 12),
                Icon(
                  investment.isPositiveReturn()
                      ? Icons.trending_up
                      : Icons.trending_down,
                  size: 16,
                  color: color,
                ),
                const SizedBox(width: AppSpacing.xs),
                Text(
                  investment.getFormattedGainLoss(),
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: color,
                  ),
                ),
              ],
            ),
          ],
        ),
        trailing: Icon(
          Icons.chevron_right,
          color: isDark ? AppColors.textOnDarkTertiary : AppColors.textOnLightTertiary,
        ),
        onTap: () async {
          await context.push('/dashboard/investments/${investment.id}');
          if (mounted) await _loadData();
        },
      ),
    );
  }
}
