// Mocks generated by Mockito 5.4.6 from annotations
// in plutus_fe_prototype/test/helpers/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i22;
import 'dart:typed_data' as _i38;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:plutus_fe_prototype/models/ai/category_context.dart' as _i33;
import 'package:plutus_fe_prototype/models/ai/category_suggestion.dart' as _i30;
import 'package:plutus_fe_prototype/models/ai/correction.dart' as _i31;
import 'package:plutus_fe_prototype/models/ai/insight.dart' as _i8;
import 'package:plutus_fe_prototype/models/backup_models.dart' as _i16;
import 'package:plutus_fe_prototype/models/bill_model.dart' as _i18;
import 'package:plutus_fe_prototype/models/budget_model.dart' as _i7;
import 'package:plutus_fe_prototype/models/investment_model.dart' as _i2;
import 'package:plutus_fe_prototype/models/investment_price_point.dart' as _i3;
import 'package:plutus_fe_prototype/models/investment_sale.dart' as _i19;
import 'package:plutus_fe_prototype/models/market_data_model.dart' as _i26;
import 'package:plutus_fe_prototype/models/profile_model.dart' as _i6;
import 'package:plutus_fe_prototype/models/report_config.dart' as _i35;
import 'package:plutus_fe_prototype/models/report_data.dart' as _i36;
import 'package:plutus_fe_prototype/models/transaction_model.dart' as _i14;
import 'package:plutus_fe_prototype/models/user_model.dart' as _i5;
import 'package:plutus_fe_prototype/services/interfaces/i_ai_category_pipeline.dart'
    as _i32;
import 'package:plutus_fe_prototype/services/interfaces/i_ai_service.dart'
    as _i29;
import 'package:plutus_fe_prototype/services/interfaces/i_backend_ffi_service.dart'
    as _i11;
import 'package:plutus_fe_prototype/services/interfaces/i_backup_service.dart'
    as _i15;
import 'package:plutus_fe_prototype/services/interfaces/i_bill_service.dart'
    as _i17;
import 'package:plutus_fe_prototype/services/interfaces/i_budget_service.dart'
    as _i28;
import 'package:plutus_fe_prototype/services/interfaces/i_consent_service.dart'
    as _i39;
import 'package:plutus_fe_prototype/services/interfaces/i_database_service.dart'
    as _i9;
import 'package:plutus_fe_prototype/services/interfaces/i_google_auth_service.dart'
    as _i24;
import 'package:plutus_fe_prototype/services/interfaces/i_insights_service.dart'
    as _i40;
import 'package:plutus_fe_prototype/services/interfaces/i_investment_service.dart'
    as _i4;
import 'package:plutus_fe_prototype/services/interfaces/i_price_api_service.dart'
    as _i25;
import 'package:plutus_fe_prototype/services/interfaces/i_profile_service.dart'
    as _i21;
import 'package:plutus_fe_prototype/services/interfaces/i_report_ai_service.dart'
    as _i34;
import 'package:plutus_fe_prototype/services/interfaces/i_report_pdf_service.dart'
    as _i37;
import 'package:plutus_fe_prototype/services/interfaces/i_settings_service.dart'
    as _i23;
import 'package:plutus_fe_prototype/services/interfaces/i_sync_manager.dart'
    as _i27;
import 'package:plutus_fe_prototype/services/interfaces/i_transaction_service.dart'
    as _i13;
import 'package:plutus_fe_prototype/services/interfaces/i_user_service.dart'
    as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInvestmentModel_0 extends _i1.SmartFake
    implements _i2.InvestmentModel {
  _FakeInvestmentModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvestmentPricePoint_1 extends _i1.SmartFake
    implements _i3.InvestmentPricePoint {
  _FakeInvestmentPricePoint_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecordSaleResult_2 extends _i1.SmartFake
    implements _i4.RecordSaleResult {
  _FakeRecordSaleResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_3 extends _i1.SmartFake implements _i5.User {
  _FakeUser_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_4 extends _i1.SmartFake implements _i6.Profile {
  _FakeProfile_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudget_5 extends _i1.SmartFake implements _i7.Budget {
  _FakeBudget_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBudgetCategory_6 extends _i1.SmartFake
    implements _i7.BudgetCategory {
  _FakeBudgetCategory_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsightsResponse_7 extends _i1.SmartFake
    implements _i8.InsightsResponse {
  _FakeInsightsResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatabaseService extends _i1.Mock implements _i9.IDatabaseService {
  MockIDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<dynamic> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<int> createUser({
    required String? username,
    required String? displayName,
    String? email,
    String? oauthProvider,
    String? oauthId,
    bool? isGuest = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [], {
              #username: username,
              #displayName: displayName,
              #email: email,
              #oauthProvider: oauthProvider,
              #oauthId: oauthId,
              #isGuest: isGuest,
            }),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>?> getUserByOAuth(
    String? provider,
    String? oauthId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByOAuth, [provider, oauthId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> updateUserLastLogin(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserLastLogin, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> linkOAuthToUser(
    int? userId,
    String? provider,
    String? oauthId,
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkOAuthToUser, [
              userId,
              provider,
              oauthId,
              email,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> unlinkOAuthFromUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkOAuthFromUser, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertTransaction(
    int? userId,
    Map<String, dynamic>? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertTransaction, [userId, transaction]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getPostingsByTransactionId(
    int? transactionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPostingsByTransactionId, [transactionId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getTransactionsByUserId(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTransactionsByUserId, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> deleteTransaction(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [transactionId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteTransactionById(String? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransactionById, [transactionId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> markTransactionAsSynced(int? transactionId) =>
      (super.noSuchMethod(
            Invocation.method(#markTransactionAsSynced, [transactionId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getUnsyncedTransactions(
    int? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTransactions, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> setSetting(int? userId, String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSetting, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getSetting(int? userId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getSetting, [userId, key]),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<Map<String, String>> getAllSettings(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSettings, [userId]),
            returnValue: _i10.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i10.Future<Map<String, String>>);

  @override
  _i10.Future<void> deleteSetting(int? userId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSetting, [userId, key]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> createProfile(_i6.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [profile]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> getProfileByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileByUserId, [userId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> updateProfile(_i6.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteProfile(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertBill(int? userId, Map<String, dynamic>? bill) =>
      (super.noSuchMethod(
            Invocation.method(#insertBill, [userId, bill]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getBillsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBillsByUserId, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> updateBill(int? billId, Map<String, dynamic>? bill) =>
      (super.noSuchMethod(
            Invocation.method(#updateBill, [billId, bill]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBill(int? billId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [billId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertInvestment(
    int? userId,
    Map<String, dynamic>? investment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#insertInvestment, [userId, investment]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getInvestmentsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentsByUserId, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>?> getInvestmentById(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentById, [investmentId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> updateInvestment(
    String? investmentId,
    Map<String, dynamic>? investment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInvestment, [investmentId, investment]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteInvestment(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInvestment, [investmentId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> markInvestmentAsSynced(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#markInvestmentAsSynced, [investmentId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getUnsyncedInvestments(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedInvestments, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<int> insertInvestmentPricePoint(Map<String, dynamic>? point) =>
      (super.noSuchMethod(
            Invocation.method(#insertInvestmentPricePoint, [point]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getInvestmentPricePoints(
    String? investmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentPricePoints, [investmentId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>?> getLatestInvestmentPricePoint(
    String? investmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestInvestmentPricePoint, [investmentId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> deleteInvestmentPricePoint(int? pointId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInvestmentPricePoint, [pointId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertInvestmentSale(Map<String, dynamic>? sale) =>
      (super.noSuchMethod(
            Invocation.method(#insertInvestmentSale, [sale]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getInvestmentSales(
    String? investmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentSales, [investmentId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> setUserDataConsent(int? userId, bool? consent) =>
      (super.noSuchMethod(
            Invocation.method(#setUserDataConsent, [userId, consent]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertBudget(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertBudget, [data]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getBudgetsByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetsByUserId, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>?> getActiveBudgetByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBudgetByUserId, [userId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> updateBudget(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudget, [id, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBudget(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertBudgetCategory(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertBudgetCategory, [data]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getBudgetCategoriesByBudgetId(
    int? budgetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetCategoriesByBudgetId, [budgetId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> updateBudgetCategory(int? id, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateBudgetCategory, [id, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBudgetCategory(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudgetCategory, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBudgetCategoriesByBudgetId(int? budgetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudgetCategoriesByBudgetId, [budgetId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertBudgetPeriod(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertBudgetPeriod, [data]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getBudgetPeriodsByCategoryId(
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetPeriodsByCategoryId, [categoryId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>?> getBudgetPeriodForDate(
    int? categoryId,
    String? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBudgetPeriodForDate, [categoryId, date]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> deleteBudgetPeriodsByCategoryId(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudgetPeriodsByCategoryId, [categoryId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int> insertNotificationRule(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insertNotificationRule, [data]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getNotificationRulesByCategoryId(
    int? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationRulesByCategoryId, [categoryId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> updateNotificationRule(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationRule, [id, data]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteNotificationRulesByCategoryId(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotificationRulesByCategoryId, [
              categoryId,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getExpensePostingsForPeriod(
    int? userId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpensePostingsForPeriod, [
              userId,
              startDate,
              endDate,
            ]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> insertAICorrection(Map<String, dynamic>? correction) =>
      (super.noSuchMethod(
            Invocation.method(#insertAICorrection, [correction]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getAICorrections(
    String? feature, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAICorrections, [feature], {#limit: limit}),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearUserData(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> resetConnection() =>
      (super.noSuchMethod(
            Invocation.method(#resetConnection, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IBackendFfiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBackendFfiService extends _i1.Mock
    implements _i11.IBackendFfiService {
  MockIBackendFfiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable =>
      (super.noSuchMethod(Invocation.getter(#isAvailable), returnValue: false)
          as bool);

  @override
  String constructJournal(String? journalJson) =>
      (super.noSuchMethod(
            Invocation.method(#constructJournal, [journalJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#constructJournal, [journalJson]),
            ),
          )
          as String);

  @override
  String dumpJournal() =>
      (super.noSuchMethod(
            Invocation.method(#dumpJournal, []),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#dumpJournal, []),
            ),
          )
          as String);

  @override
  String addTransaction(String? transactionJson) =>
      (super.noSuchMethod(
            Invocation.method(#addTransaction, [transactionJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#addTransaction, [transactionJson]),
            ),
          )
          as String);

  @override
  String addInvestment(String? transactionJson) =>
      (super.noSuchMethod(
            Invocation.method(#addInvestment, [transactionJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#addInvestment, [transactionJson]),
            ),
          )
          as String);

  @override
  String addBudget(String? budgetJson) =>
      (super.noSuchMethod(
            Invocation.method(#addBudget, [budgetJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#addBudget, [budgetJson]),
            ),
          )
          as String);

  @override
  String deleteBudget(String? accountName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [accountName]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#deleteBudget, [accountName]),
            ),
          )
          as String);

  @override
  String budgetReport(String? requestJson) =>
      (super.noSuchMethod(
            Invocation.method(#budgetReport, [requestJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#budgetReport, [requestJson]),
            ),
          )
          as String);

  @override
  String addRate(String? rateJson) =>
      (super.noSuchMethod(
            Invocation.method(#addRate, [rateJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#addRate, [rateJson]),
            ),
          )
          as String);

  @override
  String getRate(String? requestJson) =>
      (super.noSuchMethod(
            Invocation.method(#getRate, [requestJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getRate, [requestJson]),
            ),
          )
          as String);

  @override
  String accountList() =>
      (super.noSuchMethod(
            Invocation.method(#accountList, []),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#accountList, []),
            ),
          )
          as String);

  @override
  String commodities() =>
      (super.noSuchMethod(
            Invocation.method(#commodities, []),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#commodities, []),
            ),
          )
          as String);

  @override
  String getInvestmentReport(String? requestJson) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentReport, [requestJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getInvestmentReport, [requestJson]),
            ),
          )
          as String);

  @override
  String getIncomeReport() =>
      (super.noSuchMethod(
            Invocation.method(#getIncomeReport, []),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getIncomeReport, []),
            ),
          )
          as String);

  @override
  String getSavingsReport(String? requestJson) =>
      (super.noSuchMethod(
            Invocation.method(#getSavingsReport, [requestJson]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getSavingsReport, [requestJson]),
            ),
          )
          as String);
}

/// A class which mocks [ITransactionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionService extends _i1.Mock
    implements _i13.ITransactionService {
  MockITransactionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<List<_i14.Transaction>> get transactionStream =>
      (super.noSuchMethod(
            Invocation.getter(#transactionStream),
            returnValue: _i10.Stream<List<_i14.Transaction>>.empty(),
          )
          as _i10.Stream<List<_i14.Transaction>>);

  @override
  List<_i14.Transaction> getLastCachedTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getLastCachedTransactions, []),
            returnValue: <_i14.Transaction>[],
          )
          as List<_i14.Transaction>);

  @override
  void setCurrentUser(int? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUser, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyTransactionUpdate() => super.noSuchMethod(
    Invocation.method(#notifyTransactionUpdate, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<List<_i14.Transaction>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i10.Future<List<_i14.Transaction>>.value(
              <_i14.Transaction>[],
            ),
          )
          as _i10.Future<List<_i14.Transaction>>);

  @override
  _i10.Future<void> importTransactionFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#importTransactionFile, [filePath]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> importTransaction(Map<String, dynamic>? transaction) =>
      (super.noSuchMethod(
            Invocation.method(#importTransaction, [transaction]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> parseJsonFile(String? jsonContent) =>
      (super.noSuchMethod(
            Invocation.method(#parseJsonFile, [jsonContent]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> parseCsvFile(String? csvContent) =>
      (super.noSuchMethod(
            Invocation.method(#parseCsvFile, [csvContent]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> parseXmlFile(String? xmlContent) =>
      (super.noSuchMethod(
            Invocation.method(#parseXmlFile, [xmlContent]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> parseLedgerFile(
    String? ledgerContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseLedgerFile, [ledgerContent]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getUnsyncedTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedTransactions, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> syncPendingTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingTransactions, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBackupService extends _i1.Mock implements _i15.IBackupService {
  MockIBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> getDatabasePath() =>
      (super.noSuchMethod(
            Invocation.method(#getDatabasePath, []),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getDatabasePath, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<String> uploadBackup(String? backupKey) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBackup, [backupKey]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#uploadBackup, [backupKey]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> restoreBackup(String? backupKey, String? s3ObjectKey) =>
      (super.noSuchMethod(
            Invocation.method(#restoreBackup, [backupKey, s3ObjectKey]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i16.VersionEntry>> listBackups(String? backupKey) =>
      (super.noSuchMethod(
            Invocation.method(#listBackups, [backupKey]),
            returnValue: _i10.Future<List<_i16.VersionEntry>>.value(
              <_i16.VersionEntry>[],
            ),
          )
          as _i10.Future<List<_i16.VersionEntry>>);

  @override
  _i10.Future<void> deleteBackup(String? s3ObjectKey) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBackup, [s3ObjectKey]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getLatestBackupChecksum(String? backupKey) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestBackupChecksum, [backupKey]),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<String> computeLocalChecksum() =>
      (super.noSuchMethod(
            Invocation.method(#computeLocalChecksum, []),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#computeLocalChecksum, []),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> enforceVersionLimit(String? backupKey) =>
      (super.noSuchMethod(
            Invocation.method(#enforceVersionLimit, [backupKey]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IBillService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBillService extends _i1.Mock implements _i17.IBillService {
  MockIBillService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<List<_i18.Bill>> get billStream =>
      (super.noSuchMethod(
            Invocation.getter(#billStream),
            returnValue: _i10.Stream<List<_i18.Bill>>.empty(),
          )
          as _i10.Stream<List<_i18.Bill>>);

  @override
  void setCurrentUser(int? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUser, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> notifyBillUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#notifyBillUpdate, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i18.Bill>> getBills() =>
      (super.noSuchMethod(
            Invocation.method(#getBills, []),
            returnValue: _i10.Future<List<_i18.Bill>>.value(<_i18.Bill>[]),
          )
          as _i10.Future<List<_i18.Bill>>);

  @override
  _i10.Future<void> addBill(_i18.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#addBill, [bill]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> updateBill(_i18.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#updateBill, [bill]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteBill(int? billId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [billId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> markBillAsPaid(int? billId) =>
      (super.noSuchMethod(
            Invocation.method(#markBillAsPaid, [billId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<double> getTotalDueAmount({
    required String? currency,
    int? days = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalDueAmount, [], {
              #currency: currency,
              #days: days,
            }),
            returnValue: _i10.Future<double>.value(0.0),
          )
          as _i10.Future<double>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IInvestmentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIInvestmentService extends _i1.Mock
    implements _i4.IInvestmentService {
  MockIInvestmentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<void> get onChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onChanged),
            returnValue: _i10.Stream<void>.empty(),
          )
          as _i10.Stream<void>);

  @override
  void setUserId(int? userId) => super.noSuchMethod(
    Invocation.method(#setUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<List<_i2.InvestmentModel>> getInvestmentList({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentList, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i10.Future<List<_i2.InvestmentModel>>.value(
              <_i2.InvestmentModel>[],
            ),
          )
          as _i10.Future<List<_i2.InvestmentModel>>);

  @override
  _i10.Future<List<_i2.InvestmentModel>> getActiveInvestments({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveInvestments, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i10.Future<List<_i2.InvestmentModel>>.value(
              <_i2.InvestmentModel>[],
            ),
          )
          as _i10.Future<List<_i2.InvestmentModel>>);

  @override
  _i10.Future<List<_i2.InvestmentModel>> getClosedInvestments({
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getClosedInvestments, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i10.Future<List<_i2.InvestmentModel>>.value(
              <_i2.InvestmentModel>[],
            ),
          )
          as _i10.Future<List<_i2.InvestmentModel>>);

  @override
  _i10.Future<_i2.InvestmentModel> getInvestmentDetail(String? commodity) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentDetail, [commodity]),
            returnValue: _i10.Future<_i2.InvestmentModel>.value(
              _FakeInvestmentModel_0(
                this,
                Invocation.method(#getInvestmentDetail, [commodity]),
              ),
            ),
          )
          as _i10.Future<_i2.InvestmentModel>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> deleteInvestment(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInvestment, [investmentId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> saveInvestment(_i2.InvestmentModel? investment) =>
      (super.noSuchMethod(
            Invocation.method(#saveInvestment, [investment]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#saveInvestment, [investment]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  double getTotalPortfolioValue(List<_i2.InvestmentModel>? investments) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalPortfolioValue, [investments]),
            returnValue: 0.0,
          )
          as double);

  @override
  double getTotalGainLoss(List<_i2.InvestmentModel>? investments) =>
      (super.noSuchMethod(
            Invocation.method(#getTotalGainLoss, [investments]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i10.Future<_i2.InvestmentModel> refreshPriceData(
    _i2.InvestmentModel? investment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshPriceData, [investment]),
            returnValue: _i10.Future<_i2.InvestmentModel>.value(
              _FakeInvestmentModel_0(
                this,
                Invocation.method(#refreshPriceData, [investment]),
              ),
            ),
          )
          as _i10.Future<_i2.InvestmentModel>);

  @override
  _i10.Future<Map<String, dynamic>> getInvestmentReport({String? currency}) =>
      (super.noSuchMethod(
            Invocation.method(#getInvestmentReport, [], {#currency: currency}),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getUnsyncedInvestments(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedInvestments, [userId]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<void> markInvestmentAsSynced(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#markInvestmentAsSynced, [investmentId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i3.InvestmentPricePoint> addPricePoint({
    required String? investmentId,
    required DateTime? date,
    required double? price,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addPricePoint, [], {
              #investmentId: investmentId,
              #date: date,
              #price: price,
              #note: note,
            }),
            returnValue: _i10.Future<_i3.InvestmentPricePoint>.value(
              _FakeInvestmentPricePoint_1(
                this,
                Invocation.method(#addPricePoint, [], {
                  #investmentId: investmentId,
                  #date: date,
                  #price: price,
                  #note: note,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.InvestmentPricePoint>);

  @override
  _i10.Future<List<_i3.InvestmentPricePoint>> getPricePoints(
    String? investmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPricePoints, [investmentId]),
            returnValue: _i10.Future<List<_i3.InvestmentPricePoint>>.value(
              <_i3.InvestmentPricePoint>[],
            ),
          )
          as _i10.Future<List<_i3.InvestmentPricePoint>>);

  @override
  _i10.Future<void> deletePricePoint(int? pointId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePricePoint, [pointId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i4.RecordSaleResult> recordSale({
    required String? investmentId,
    required double? quantity,
    required double? pricePerUnit,
    required DateTime? date,
    required String? cashAccount,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordSale, [], {
              #investmentId: investmentId,
              #quantity: quantity,
              #pricePerUnit: pricePerUnit,
              #date: date,
              #cashAccount: cashAccount,
              #notes: notes,
            }),
            returnValue: _i10.Future<_i4.RecordSaleResult>.value(
              _FakeRecordSaleResult_2(
                this,
                Invocation.method(#recordSale, [], {
                  #investmentId: investmentId,
                  #quantity: quantity,
                  #pricePerUnit: pricePerUnit,
                  #date: date,
                  #cashAccount: cashAccount,
                  #notes: notes,
                }),
              ),
            ),
          )
          as _i10.Future<_i4.RecordSaleResult>);

  @override
  _i10.Future<List<_i19.InvestmentSale>> getSales(String? investmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getSales, [investmentId]),
            returnValue: _i10.Future<List<_i19.InvestmentSale>>.value(
              <_i19.InvestmentSale>[],
            ),
          )
          as _i10.Future<List<_i19.InvestmentSale>>);
}

/// A class which mocks [IUserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserService extends _i1.Mock implements _i20.IUserService {
  MockIUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i5.User> createLocalUser({
    required String? username,
    required String? displayName,
    bool? isGuest = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createLocalUser, [], {
              #username: username,
              #displayName: displayName,
              #isGuest: isGuest,
            }),
            returnValue: _i10.Future<_i5.User>.value(
              _FakeUser_3(
                this,
                Invocation.method(#createLocalUser, [], {
                  #username: username,
                  #displayName: displayName,
                  #isGuest: isGuest,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.User>);

  @override
  _i10.Future<_i5.User> createOAuthUser({
    required String? username,
    required String? displayName,
    required String? email,
    required String? oauthProvider,
    required String? oauthId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOAuthUser, [], {
              #username: username,
              #displayName: displayName,
              #email: email,
              #oauthProvider: oauthProvider,
              #oauthId: oauthId,
            }),
            returnValue: _i10.Future<_i5.User>.value(
              _FakeUser_3(
                this,
                Invocation.method(#createOAuthUser, [], {
                  #username: username,
                  #displayName: displayName,
                  #email: email,
                  #oauthProvider: oauthProvider,
                  #oauthId: oauthId,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.User>);

  @override
  _i10.Future<_i5.User?> getUserById(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i10.Future<_i5.User?>.value(),
          )
          as _i10.Future<_i5.User?>);

  @override
  _i10.Future<_i5.User?> getUserByUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByUsername, [username]),
            returnValue: _i10.Future<_i5.User?>.value(),
          )
          as _i10.Future<_i5.User?>);

  @override
  _i10.Future<_i5.User?> getUserByOAuth(String? provider, String? oauthId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByOAuth, [provider, oauthId]),
            returnValue: _i10.Future<_i5.User?>.value(),
          )
          as _i10.Future<_i5.User?>);

  @override
  _i10.Future<List<_i5.User>> getAllUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, []),
            returnValue: _i10.Future<List<_i5.User>>.value(<_i5.User>[]),
          )
          as _i10.Future<List<_i5.User>>);

  @override
  _i10.Future<void> updateLastLogin(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastLogin, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> linkOAuthToUser({
    required int? userId,
    required String? provider,
    required String? oauthId,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#linkOAuthToUser, [], {
              #userId: userId,
              #provider: provider,
              #oauthId: oauthId,
              #email: email,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> unlinkOAuthFromUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unlinkOAuthFromUser, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> clearUserData(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileService extends _i1.Mock implements _i21.IProfileService {
  MockIProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i6.Profile> createProfile({
    required int? userId,
    String? avatarPath,
    String? dateOfBirth,
    String? position,
    String? placeOfEmployment,
    bool? showName = true,
    bool? showEmail = true,
    bool? showDateOfBirth = false,
    bool? showPosition = false,
    bool? showPlaceOfEmployment = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createProfile, [], {
              #userId: userId,
              #avatarPath: avatarPath,
              #dateOfBirth: dateOfBirth,
              #position: position,
              #placeOfEmployment: placeOfEmployment,
              #showName: showName,
              #showEmail: showEmail,
              #showDateOfBirth: showDateOfBirth,
              #showPosition: showPosition,
              #showPlaceOfEmployment: showPlaceOfEmployment,
            }),
            returnValue: _i10.Future<_i6.Profile>.value(
              _FakeProfile_4(
                this,
                Invocation.method(#createProfile, [], {
                  #userId: userId,
                  #avatarPath: avatarPath,
                  #dateOfBirth: dateOfBirth,
                  #position: position,
                  #placeOfEmployment: placeOfEmployment,
                  #showName: showName,
                  #showEmail: showEmail,
                  #showDateOfBirth: showDateOfBirth,
                  #showPosition: showPosition,
                  #showPlaceOfEmployment: showPlaceOfEmployment,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.Profile>);

  @override
  _i10.Future<_i6.Profile?> getProfileByUserId(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileByUserId, [userId]),
            returnValue: _i10.Future<_i6.Profile?>.value(),
          )
          as _i10.Future<_i6.Profile?>);

  @override
  _i10.Future<_i6.Profile> updateProfile(_i6.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i10.Future<_i6.Profile>.value(
              _FakeProfile_4(
                this,
                Invocation.method(#updateProfile, [profile]),
              ),
            ),
          )
          as _i10.Future<_i6.Profile>);

  @override
  _i10.Future<String> saveAvatarImage(_i22.File? imageFile, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#saveAvatarImage, [imageFile, userId]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#saveAvatarImage, [imageFile, userId]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> deleteAvatarImage(String? avatarPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAvatarImage, [avatarPath]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteProfile(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [userId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [ISettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockISettingsService extends _i1.Mock implements _i23.ISettingsService {
  MockISettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> setString(int? userId, String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getString(
    int? userId,
    String? key, {
    String? defaultValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getString,
              [userId, key],
              {#defaultValue: defaultValue},
            ),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<void> setInt(int? userId, String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<int?> getInt(int? userId, String? key, {int? defaultValue}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getInt,
              [userId, key],
              {#defaultValue: defaultValue},
            ),
            returnValue: _i10.Future<int?>.value(),
          )
          as _i10.Future<int?>);

  @override
  _i10.Future<void> setDouble(int? userId, String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<double?> getDouble(
    int? userId,
    String? key, {
    double? defaultValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getDouble,
              [userId, key],
              {#defaultValue: defaultValue},
            ),
            returnValue: _i10.Future<double?>.value(),
          )
          as _i10.Future<double?>);

  @override
  _i10.Future<void> setBool(int? userId, String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool?> getBool(int? userId, String? key, {bool? defaultValue}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getBool,
              [userId, key],
              {#defaultValue: defaultValue},
            ),
            returnValue: _i10.Future<bool?>.value(),
          )
          as _i10.Future<bool?>);

  @override
  _i10.Future<void> setMap(
    int? userId,
    String? key,
    Map<String, dynamic>? value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setMap, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> getMap(int? userId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getMap, [userId, key]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> setList(int? userId, String? key, List<dynamic>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setList, [userId, key, value]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<dynamic>?> getList(int? userId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getList, [userId, key]),
            returnValue: _i10.Future<List<dynamic>?>.value(),
          )
          as _i10.Future<List<dynamic>?>);

  @override
  _i10.Future<Map<String, String>> getAllSettings(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSettings, [userId]),
            returnValue: _i10.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i10.Future<Map<String, String>>);

  @override
  _i10.Future<void> deleteSetting(int? userId, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSetting, [userId, key]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setThemeMode(int? userId, String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [userId, mode]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> getThemeMode(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getThemeMode, [userId]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getThemeMode, [userId]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> setDefaultCurrency(int? userId, String? currency) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultCurrency, [userId, currency]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> getDefaultCurrency(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getDefaultCurrency, [userId]),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#getDefaultCurrency, [userId]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> setNotificationsEnabled(int? userId, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationsEnabled, [userId, enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> getNotificationsEnabled(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsEnabled, [userId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> setAutoBackupEnabled(int? userId, bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoBackupEnabled, [userId, enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> getAutoBackupEnabled(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getAutoBackupEnabled, [userId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> setLastSyncTime(int? userId, DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastSyncTime, [userId, time]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<DateTime?> getLastSyncTime(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastSyncTime, [userId]),
            returnValue: _i10.Future<DateTime?>.value(),
          )
          as _i10.Future<DateTime?>);
}

/// A class which mocks [IGoogleAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGoogleAuthService extends _i1.Mock
    implements _i24.IGoogleAuthService {
  MockIGoogleAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<dynamic> get authenticationState =>
      (super.noSuchMethod(
            Invocation.getter(#authenticationState),
            returnValue: _i10.Stream<dynamic>.empty(),
          )
          as _i10.Stream<dynamic>);

  @override
  _i10.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>> getSessionInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionInfo, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);
}

/// A class which mocks [IPriceApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPriceApiService extends _i1.Mock implements _i25.IPriceApiService {
  MockIPriceApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<double?> getCurrentPrice(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPrice, [symbol]),
            returnValue: _i10.Future<double?>.value(),
          )
          as _i10.Future<double?>);

  @override
  _i10.Future<List<Map<String, dynamic>>?> getHistoricalPrices(
    String? symbol,
    int? days,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHistoricalPrices, [symbol, days]),
            returnValue: _i10.Future<List<Map<String, dynamic>>?>.value(),
          )
          as _i10.Future<List<Map<String, dynamic>>?>);

  @override
  _i10.Future<_i26.MarketData?> getMarketData(String? symbol) =>
      (super.noSuchMethod(
            Invocation.method(#getMarketData, [symbol]),
            returnValue: _i10.Future<_i26.MarketData?>.value(),
          )
          as _i10.Future<_i26.MarketData?>);
}

/// A class which mocks [ISyncManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockISyncManager extends _i1.Mock implements _i27.ISyncManager {
  MockISyncManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAutoSyncActive =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoSyncActive),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasPendingUploads =>
      (super.noSuchMethod(
            Invocation.getter(#hasPendingUploads),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Future<_i16.ConflictResult> checkConflictOnLaunch(String? backupKey) =>
      (super.noSuchMethod(
            Invocation.method(#checkConflictOnLaunch, [backupKey]),
            returnValue: _i10.Future<_i16.ConflictResult>.value(
              _i16.ConflictResult.match,
            ),
          )
          as _i10.Future<_i16.ConflictResult>);

  @override
  void startAutoSync(String? backupKey) => super.noSuchMethod(
    Invocation.method(#startAutoSync, [backupKey]),
    returnValueForMissingStub: null,
  );

  @override
  void stopAutoSync() => super.noSuchMethod(
    Invocation.method(#stopAutoSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void onConnectivityChanged(bool? isConnected) => super.noSuchMethod(
    Invocation.method(#onConnectivityChanged, [isConnected]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [IBudgetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBudgetService extends _i1.Mock implements _i28.IBudgetService {
  MockIBudgetService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i7.Budget?> get budgetStream =>
      (super.noSuchMethod(
            Invocation.getter(#budgetStream),
            returnValue: _i10.Stream<_i7.Budget?>.empty(),
          )
          as _i10.Stream<_i7.Budget?>);

  @override
  void setCurrentUser(int? userId) => super.noSuchMethod(
    Invocation.method(#setCurrentUser, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> notifyBudgetUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#notifyBudgetUpdate, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.Budget> createBudget({
    required String? name,
    required _i7.BudgetMode? mode,
    required _i7.BudgetPeriodType? periodType,
    required String? currencyCode,
    DateTime? periodStart,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBudget, [], {
              #name: name,
              #mode: mode,
              #periodType: periodType,
              #currencyCode: currencyCode,
              #periodStart: periodStart,
            }),
            returnValue: _i10.Future<_i7.Budget>.value(
              _FakeBudget_5(
                this,
                Invocation.method(#createBudget, [], {
                  #name: name,
                  #mode: mode,
                  #periodType: periodType,
                  #currencyCode: currencyCode,
                  #periodStart: periodStart,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.Budget>);

  @override
  _i10.Future<_i7.Budget?> getActiveBudget() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveBudget, []),
            returnValue: _i10.Future<_i7.Budget?>.value(),
          )
          as _i10.Future<_i7.Budget?>);

  @override
  _i10.Future<_i7.Budget> updateBudget(
    int? budgetId, {
    String? name,
    _i7.BudgetMode? mode,
    _i7.BudgetPeriodType? periodType,
    String? currencyCode,
    DateTime? periodStart,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBudget,
              [budgetId],
              {
                #name: name,
                #mode: mode,
                #periodType: periodType,
                #currencyCode: currencyCode,
                #periodStart: periodStart,
              },
            ),
            returnValue: _i10.Future<_i7.Budget>.value(
              _FakeBudget_5(
                this,
                Invocation.method(
                  #updateBudget,
                  [budgetId],
                  {
                    #name: name,
                    #mode: mode,
                    #periodType: periodType,
                    #currencyCode: currencyCode,
                    #periodStart: periodStart,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.Budget>);

  @override
  _i10.Future<void> deleteBudget(int? budgetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBudget, [budgetId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.BudgetCategory> addCategory({
    required int? budgetId,
    required String? name,
    required List<String>? accountPatterns,
    required double? amount,
    String? icon,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [], {
              #budgetId: budgetId,
              #name: name,
              #accountPatterns: accountPatterns,
              #amount: amount,
              #icon: icon,
            }),
            returnValue: _i10.Future<_i7.BudgetCategory>.value(
              _FakeBudgetCategory_6(
                this,
                Invocation.method(#addCategory, [], {
                  #budgetId: budgetId,
                  #name: name,
                  #accountPatterns: accountPatterns,
                  #amount: amount,
                  #icon: icon,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.BudgetCategory>);

  @override
  _i10.Future<_i7.BudgetCategory> updateCategory(
    int? categoryId, {
    String? name,
    List<String>? accountPatterns,
    double? budgetedAmount,
    bool? rolloverEnabled,
    _i7.RolloverBehavior? rolloverBehavior,
    String? icon,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateCategory,
              [categoryId],
              {
                #name: name,
                #accountPatterns: accountPatterns,
                #budgetedAmount: budgetedAmount,
                #rolloverEnabled: rolloverEnabled,
                #rolloverBehavior: rolloverBehavior,
                #icon: icon,
              },
            ),
            returnValue: _i10.Future<_i7.BudgetCategory>.value(
              _FakeBudgetCategory_6(
                this,
                Invocation.method(
                  #updateCategory,
                  [categoryId],
                  {
                    #name: name,
                    #accountPatterns: accountPatterns,
                    #budgetedAmount: budgetedAmount,
                    #rolloverEnabled: rolloverEnabled,
                    #rolloverBehavior: rolloverBehavior,
                    #icon: icon,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i7.BudgetCategory>);

  @override
  _i10.Future<void> removeCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCategory, [categoryId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> reorderCategories(int? budgetId, List<int>? categoryIds) =>
      (super.noSuchMethod(
            Invocation.method(#reorderCategories, [budgetId, categoryIds]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<Map<int, double>> getAllCategorySpending(
    int? budgetId,
    DateTime? periodStart,
    DateTime? periodEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategorySpending, [
              budgetId,
              periodStart,
              periodEnd,
            ]),
            returnValue: _i10.Future<Map<int, double>>.value(<int, double>{}),
          )
          as _i10.Future<Map<int, double>>);

  @override
  _i10.Future<List<_i7.UnbudgetedEntry>> getUnbudgetedSpending(
    int? budgetId,
    DateTime? periodStart,
    DateTime? periodEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnbudgetedSpending, [
              budgetId,
              periodStart,
              periodEnd,
            ]),
            returnValue: _i10.Future<List<_i7.UnbudgetedEntry>>.value(
              <_i7.UnbudgetedEntry>[],
            ),
          )
          as _i10.Future<List<_i7.UnbudgetedEntry>>);

  @override
  _i10.Future<List<_i7.SuggestedCategory>> suggestCategoriesFromAccounts() =>
      (super.noSuchMethod(
            Invocation.method(#suggestCategoriesFromAccounts, []),
            returnValue: _i10.Future<List<_i7.SuggestedCategory>>.value(
              <_i7.SuggestedCategory>[],
            ),
          )
          as _i10.Future<List<_i7.SuggestedCategory>>);

  @override
  _i10.Future<double> calculateRollover(int? categoryId, DateTime? periodEnd) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRollover, [categoryId, periodEnd]),
            returnValue: _i10.Future<double>.value(0.0),
          )
          as _i10.Future<double>);

  @override
  _i10.Future<void> closePeriod(int? budgetId, DateTime? periodEnd) =>
      (super.noSuchMethod(
            Invocation.method(#closePeriod, [budgetId, periodEnd]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i7.BudgetPeriod?> getPeriodForCategory(
    int? categoryId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPeriodForCategory, [categoryId, date]),
            returnValue: _i10.Future<_i7.BudgetPeriod?>.value(),
          )
          as _i10.Future<_i7.BudgetPeriod?>);

  @override
  double getProjectedSpending(
    double? currentSpent,
    DateTime? periodStart,
    DateTime? periodEnd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProjectedSpending, [
              currentSpent,
              periodStart,
              periodEnd,
            ]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i10.Future<void> setNotificationRule(
    int? categoryId,
    double? thresholdPct,
    bool? enabled,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setNotificationRule, [
              categoryId,
              thresholdPct,
              enabled,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i7.NotificationRule>> getNotificationRules(int? budgetId) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationRules, [budgetId]),
            returnValue: _i10.Future<List<_i7.NotificationRule>>.value(
              <_i7.NotificationRule>[],
            ),
          )
          as _i10.Future<List<_i7.NotificationRule>>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IAIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAIService extends _i1.Mock implements _i29.IAIService {
  MockIAIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i30.CategorySuggestion?> categorizeTransaction(
    _i14.Transaction? transaction,
    List<String>? accounts,
    List<_i31.Correction>? corrections,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#categorizeTransaction, [
              transaction,
              accounts,
              corrections,
            ]),
            returnValue: _i10.Future<_i30.CategorySuggestion?>.value(),
          )
          as _i10.Future<_i30.CategorySuggestion?>);

  @override
  _i10.Future<List<_i30.CategorySuggestion?>> categorizeBatch(
    List<_i14.Transaction>? transactions,
    List<String>? accounts,
    List<_i31.Correction>? corrections,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#categorizeBatch, [
              transactions,
              accounts,
              corrections,
            ]),
            returnValue: _i10.Future<List<_i30.CategorySuggestion?>>.value(
              <_i30.CategorySuggestion?>[],
            ),
          )
          as _i10.Future<List<_i30.CategorySuggestion?>>);
}

/// A class which mocks [IAICategoryPipeline].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAICategoryPipeline extends _i1.Mock
    implements _i32.IAICategoryPipeline {
  MockIAICategoryPipeline() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i30.CategorySuggestion>> suggest(
    _i33.CategoryContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#suggest, [context]),
            returnValue: _i10.Future<List<_i30.CategorySuggestion>>.value(
              <_i30.CategorySuggestion>[],
            ),
          )
          as _i10.Future<List<_i30.CategorySuggestion>>);

  @override
  _i10.Stream<List<_i30.CategorySuggestion>> suggestStream(
    _i33.CategoryContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#suggestStream, [context]),
            returnValue: _i10.Stream<List<_i30.CategorySuggestion>>.empty(),
          )
          as _i10.Stream<List<_i30.CategorySuggestion>>);

  @override
  _i10.Future<List<List<_i30.CategorySuggestion>>> suggestBatch(
    List<_i33.CategoryContext>? contexts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#suggestBatch, [contexts]),
            returnValue: _i10.Future<List<List<_i30.CategorySuggestion>>>.value(
              <List<_i30.CategorySuggestion>>[],
            ),
          )
          as _i10.Future<List<List<_i30.CategorySuggestion>>>);
}

/// A class which mocks [IReportAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReportAiService extends _i1.Mock implements _i34.IReportAiService {
  MockIReportAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<Map<_i35.ReportSection, _i36.SectionRecommendation>>
  getRecommendations({
    required List<_i35.ReportSection>? sections,
    required _i35.DateRange? dateRange,
    required _i35.AudienceMode? audienceMode,
    required String? locale,
    required String? privacyLevel,
    required Map<String, dynamic>? sectionData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecommendations, [], {
              #sections: sections,
              #dateRange: dateRange,
              #audienceMode: audienceMode,
              #locale: locale,
              #privacyLevel: privacyLevel,
              #sectionData: sectionData,
            }),
            returnValue:
                _i10.Future<
                  Map<_i35.ReportSection, _i36.SectionRecommendation>
                >.value(<_i35.ReportSection, _i36.SectionRecommendation>{}),
          )
          as _i10.Future<Map<_i35.ReportSection, _i36.SectionRecommendation>>);
}

/// A class which mocks [IReportPdfService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIReportPdfService extends _i1.Mock implements _i37.IReportPdfService {
  MockIReportPdfService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> generatePdf({
    required _i36.ReportDataModel? data,
    String? locale = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePdf, [], {#data: data, #locale: locale}),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#generatePdf, [], {
                  #data: data,
                  #locale: locale,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<_i38.Uint8List> generatePdfBytes({
    required _i36.ReportDataModel? data,
    String? locale = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePdfBytes, [], {
              #data: data,
              #locale: locale,
            }),
            returnValue: _i10.Future<_i38.Uint8List>.value(_i38.Uint8List(0)),
          )
          as _i10.Future<_i38.Uint8List>);
}

/// A class which mocks [IConsentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIConsentService extends _i1.Mock implements _i39.IConsentService {
  MockIConsentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<bool> hasAcceptedTerms(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#hasAcceptedTerms, [email]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> recordAcceptance(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#recordAcceptance, [email]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [IInsightsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIInsightsService extends _i1.Mock implements _i40.IInsightsService {
  MockIInsightsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i8.InsightsResponse> generateInsights({
    required String? locale,
    required _i8.PrivacyLevel? privacyLevel,
    required List<String>? requestedTypes,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateInsights, [], {
              #locale: locale,
              #privacyLevel: privacyLevel,
              #requestedTypes: requestedTypes,
              #data: data,
            }),
            returnValue: _i10.Future<_i8.InsightsResponse>.value(
              _FakeInsightsResponse_7(
                this,
                Invocation.method(#generateInsights, [], {
                  #locale: locale,
                  #privacyLevel: privacyLevel,
                  #requestedTypes: requestedTypes,
                  #data: data,
                }),
              ),
            ),
          )
          as _i10.Future<_i8.InsightsResponse>);
}
